name: pbptyper-test

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]

jobs:
  pbptyper-tests:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - name: Checkout rpetit3/pbptyper
        uses: actions/checkout@v2

      - name: Setup miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: pbptyper
          auto-activate-base: false

      - name: Setup pbptyper Environment
        run: |
          conda install -y -c conda-forge -c bioconda rich-click executor 'python>=3.7' blast fastani

      - name: Environment Information
        run: uname -a && env

      - name: Test pbptyper basics
        run: |
          echo "Testing pbptyper"
          bin/pbptyper --version
          bin/pbptyper --help
          bin/pbptyper --check

      - name: Test pbptyper
        run: |
          echo "ERR1065617"
          bin/pbptyper --assembly test/ERR1065617.fna.gz --prefix ERR1065617 --db db/
          cat ERR1065617.tsv
          head ERR1065617-1A.tblastn.tsv
          head ERR1065617-2B.tblastn.tsv
          head ERR1065617-2X.tblastn.tsv
          echo "SRR2912551"
          bin/pbptyper --assembly test/SRR2912551.fna.gz --prefix SRR2912551 --db db/
          cat SRR2912551.tsv
          head SRR2912551-1A.tblastn.tsv
          head SRR2912551-2B.tblastn.tsv
          head SRR2912551-2X.tblastn.tsv
          echo "SRR8654742"
          bin/pbptyper --assembly test/SRR8654742.fna --prefix SRR8654742 --outdir SRR8654742
          cat SRR8654742/SRR8654742.tsv
          head SRR8654742/SRR8654742-1A.tblastn.tsv
          head SRR8654742/SRR8654742-2B.tblastn.tsv
          head SRR8654742/SRR8654742-2X.tblastn.tsv
          echo "S. pseudopneumoniae"
          bin/pbptyper --assembly test/spseudopneumoniae.fna.gz --prefix spseudopneumoniae --outdir spseudopneumoniae
          cat spseudopneumoniae/spseudopneumoniae.tsv
          head spseudopneumoniae/spseudopneumoniae-1A.tblastn.tsv
          head spseudopneumoniae/spseudopneumoniae-2B.tblastn.tsv
          head spseudopneumoniae/spseudopneumoniae-2X.tblastn.tsv
          echo "S. mitis"
          bin/pbptyper --assembly test/smitis.fna.gz --prefix smitis --outdir smitis
          cat smitis/smitis.tsv
          head smitis/smitis-1A.tblastn.tsv
          head smitis/smitis-2B.tblastn.tsv
          head smitis/smitis-2X.tblastn.tsv
          echo "S. suis"
          bin/pbptyper --assembly test/ssuis.fna.gz --prefix ssuis --outdir ssuis
          cat ssuis/ssuis.tsv
          head ssuis/ssuis-1A.tblastn.tsv
          head ssuis/ssuis-2B.tblastn.tsv
          head ssuis/ssuis-2X.tblastn.tsv
          echo "not-spn"
          bin/pbptyper --assembly test/not-spn.fna.gz --prefix not-spn
          cat not-spn.tsv
          head not-spn-1A.tblastn.tsv
          head not-spn-2B.tblastn.tsv
          head not-spn-2X.tblastn.tsv
          echo "empty"
          bin/pbptyper --assembly test/empty.fasta --prefix empty
          cat empty.tsv
          head empty-1A.tblastn.tsv
          head empty-2B.tblastn.tsv
          head empty-2X.tblastn.tsv
          echo "not-a-fasta"
          bin/pbptyper --assembly test/not-a-fasta.fasta --prefix not-a-fasta
          cat not-a-fasta.tsv
          head not-a-fasta-1A.tblastn.tsv
          head not-a-fasta-2B.tblastn.tsv
          head not-a-fasta-2X.tblastn.tsv
          echo "poor"
          bin/pbptyper --assembly test/poor.fasta --prefix poor --outdir poor
          cat poor/poor.tsv
          head poor/poor-1A.tblastn.tsv
          head poor/poor-2B.tblastn.tsv
          head poor/poor-2X.tblastn.tsv
