name: pbptyper-test

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]

jobs:
  pbptyper-tests:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - name: Checkout rpetit3/pbptyper
        uses: actions/checkout@v2

      - name: Setup miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: pbptyper
          auto-activate-base: false

      - name: Setup pbptyper Environment
        run: |
          conda install -y -c conda-forge -c bioconda 'camlhmp>=0.3.1'

      - name: Environment Information
        run: uname -a && env

      - name: Test pbptyper basics
        run: |
          echo "Testing pbptyper"
          bin/pbptyper --version
          bin/pbptyper --help

      - name: Test pbptyper
        run: |
          echo "ERR1065617"
          bin/pbptyper --yaml data/pbptyper.yaml --targets data/pbptyper.fasta --input test/ERR1065617.fna.gz --prefix ERR1065617
          cat ERR1065617.tsv
          head ERR1065617.tblastn.tsv
          echo "SRR2912551"
          bin/pbptyper --yaml data/pbptyper.yaml --targets data/pbptyper.fasta --input test/SRR2912551.fna.gz --prefix SRR2912551
          cat SRR2912551.tsv
          head SRR2912551.tblastn.tsv
          echo "SRR8654742"
          bin/pbptyper --yaml data/pbptyper.yaml --targets data/pbptyper.fasta --input test/SRR8654742.fna --prefix SRR8654742 --outdir SRR8654742
          cat SRR8654742/SRR8654742.tsv
          head SRR8654742/SRR8654742.tblastn.tsv
          echo "S. pseudopneumoniae"
          bin/pbptyper --yaml data/pbptyper.yaml --targets data/pbptyper.fasta --input test/spseudopneumoniae.fna.gz --prefix spseudopneumoniae --outdir spseudopneumoniae
          cat spseudopneumoniae/spseudopneumoniae.tsv
          head spseudopneumoniae/spseudopneumoniae.tblastn.tsv
          echo "S. mitis"
          bin/pbptyper --yaml data/pbptyper.yaml --targets data/pbptyper.fasta --input test/smitis.fna.gz --prefix smitis --outdir smitis
          cat smitis/smitis.tsv
          head smitis/smitis.tblastn.tsv
          echo "S. suis"
          bin/pbptyper --yaml data/pbptyper.yaml --targets data/pbptyper.fasta --input test/ssuis.fna.gz --prefix ssuis --outdir ssuis
          cat ssuis/ssuis.tsv
          head ssuis/ssuis.tblastn.tsv
          echo "not-spn"
          bin/pbptyper --yaml data/pbptyper.yaml --targets data/pbptyper.fasta --input test/not-spn.fna.gz --prefix not-spn
          cat not-spn.tsv
          head not-spn.tblastn.tsv
          echo "empty"
          bin/pbptyper --yaml data/pbptyper.yaml --targets data/pbptyper.fasta --input test/empty.fasta --prefix empty
          cat empty.tsv
          head empty.tblastn.tsv
          echo "not-a-fasta"
          bin/pbptyper --yaml data/pbptyper.yaml --targets data/pbptyper.fasta --input test/not-a-fasta.fasta --prefix not-a-fasta
          cat not-a-fasta.tsv
          head not-a-fasta.tblastn.tsv
          echo "poor"
          bin/pbptyper --yaml data/pbptyper.yaml --targets data/pbptyper.fasta --input test/poor.fasta --prefix poor --outdir poor
          cat poor/poor.tsv
          head poor/poor.tblastn.tsv
